# Generated by Django 2.2.7 on 2020-01-23 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20200120_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ponderation_indice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('citycode', models.CharField(max_length=5)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localities', to='location.LocalityType')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='localities',
            field=models.ManyToManyField(null=True, related_name='locations', to='location.Locality'),
        ),
    ]
