# Generated by Django 2.2.7 on 2020-01-23 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_auto_20200123_0823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='localitytype',
            old_name='name',
            new_name='label',
        ),
        migrations.RemoveField(
            model_name='locality',
            name='citycode',
        ),
    ]
