# Generated by Django 2.2.7 on 2020-01-25 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_auto_20200123_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localitytype',
            name='ponderation_indice',
        ),
    ]
