# Generated by Django 2.2.7 on 2020-01-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_remove_localitytype_ponderation_indice'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='catchphrase',
            field=models.CharField(default='unedescription', max_length=100),
            preserve_default=False,
        ),
    ]
