# Generated by Django 2.2.5 on 2019-09-21 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0007_auto_20190921_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_status', to='location.Location'),
        ),
    ]
