# Generated by Django 2.2.7 on 2020-05-30 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0008_location_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='localities',
        ),
        migrations.DeleteModel(
            name='Locality',
        ),
        migrations.DeleteModel(
            name='LocalityType',
        ),
    ]
