# Generated by Django 2.2.5 on 2019-09-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0010_auto_20190925_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='volunteers',
            field=models.ManyToManyField(null=True, related_name='volunteers', to='user.Volunteer'),
        ),
    ]
