# Generated by Django 2.2.5 on 2019-09-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0011_auto_20190925_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='slug',
            field=models.CharField(default='loc', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='volunteers',
            field=models.ManyToManyField(related_name='volunteers', to='user.Volunteer'),
        ),
    ]
