# Generated by Django 2.2.5 on 2019-09-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0012_auto_20190929_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='slug',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
