# Generated by Django 2.2.5 on 2019-10-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0015_auto_20191004_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerbase',
            name='pending_request',
            field=models.BooleanField(default=True),
        ),
    ]
