# Generated by Django 2.2.5 on 2019-10-06 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0016_volunteerbase_pending_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerbase',
            name='pending_request',
        ),
        migrations.AlterField(
            model_name='volunteerbase',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='VolunteeringRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(default='Je souhaiterais être bénévole pour votre association', max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='volunteerbase',
            name='volunteering_request',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_base', to='location.VolunteeringRequest'),
            preserve_default=False,
        ),
    ]
