# Generated by Django 2.2.5 on 2019-10-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0017_auto_20191006_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteeringrequest',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
