# Generated by Django 2.2.5 on 2019-10-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0019_auto_20191007_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteeringrequest',
            name='validated',
            field=models.BooleanField(null=True),
        ),
    ]
