# Generated by Django 2.2.6 on 2019-11-06 09:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0021_auto_20191018_1724'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='volunteerbase',
            unique_together={('volunteer', 'location')},
        ),
    ]
