# Generated by Django 2.2.7 on 2019-11-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0022_auto_20191106_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='activity',
            field=models.CharField(max_length=255),
        ),
    ]
