# Generated by Django 2.2.7 on 2019-11-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0024_status_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
