# Generated by Django 2.2.5 on 2019-09-21 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Volunteer'),
        ),
        migrations.AddField(
            model_name='location',
            name='moderator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Moderator'),
        ),
        migrations.AddField(
            model_name='location',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Status'),
        ),
        migrations.AddField(
            model_name='location',
            name='volunteers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Volunteer'),
        ),
    ]
