# Generated by Django 2.2.5 on 2019-09-21 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20190921_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='volunteers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Volunteer'),
        ),
    ]
