# Generated by Django 2.2.5 on 2019-09-21 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_auto_20190921_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='volunteer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Volunteer'),
        ),
    ]
