# Generated by Django 2.2.5 on 2019-09-21 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_auto_20190921_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Status'),
        ),
    ]
