# Generated by Django 2.2.5 on 2019-09-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_auto_20190921_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='close_date',
            field=models.DateTimeField(null=True),
        ),
    ]
