# Generated by Django 2.2.5 on 2019-09-21 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_auto_20190921_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='status',
        ),
        migrations.AddField(
            model_name='status',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='location.Location'),
            preserve_default=False,
        ),
    ]
