# Generated by Django 2.2.5 on 2019-09-25 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('location', '0009_auto_20190921_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='volunteers',
        ),
        migrations.AddField(
            model_name='location',
            name='volunteers',
            field=models.ManyToManyField(null=True, to='user.Volunteer'),
        ),
        migrations.AlterField(
            model_name='status',
            name='activity',
            field=models.CharField(default='Ouvert', max_length=255),
        ),
        migrations.AlterField(
            model_name='status',
            name='volunteer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened', to='user.Volunteer'),
        ),
    ]
