# Generated by Django 2.2.5 on 2019-10-04 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20191004_1736'),
        ('location', '0014_auto_20190929_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='location',
            name='moderator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='user.Moderator'),
        ),
        migrations.AlterField(
            model_name='location',
            name='volunteers',
            field=models.ManyToManyField(related_name='volunteers', through='location.VolunteerBase', to='user.Volunteer'),
        ),
        migrations.AddField(
            model_name='volunteerbase',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Location'),
        ),
        migrations.AddField(
            model_name='volunteerbase',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Volunteer'),
        ),
    ]
