# Generated by Django 2.2.5 on 2019-10-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0020_auto_20191008_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
