language: python
python:
        - '3.7'
install:
        - 'pip install pipenv'
        - 'pipenv install --skip-lock'
env: DJANGO_SETTINGS_MODULE=tierslieux.settings.travis

services:
        - postgresql
script:
        - python manage.py test