# Generated by Django 2.2.5 on 2019-10-04 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191001_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mod', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
