# Generated by Django 2.2.7 on 2019-11-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20191007_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='default', max_length=60, unique=True, verbose_name='username'),
            preserve_default=False,
        ),
    ]
